# Generated by Django 3.2.25 on 2025-01-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('IDEA', 'Idea'), ('PREPARATION', 'Preparation'), ('WORK', 'Work')], max_length=15)),
            ],
        ),
    ]
