# Generated by Django 3.2.25 on 2025-01-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
