# Generated by Django 3.2.25 on 2025-01-30 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_auto_20250130_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='idea',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
